name: Build RTL_433 DLL

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rtl_433forSDRSharp
  pull_request:

jobs:
  build:
    outputs:
      VERSION: ${{ steps.compute_version.outputs.VERSION }}

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup Visual Studio Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    ########################################
    # Build x86 (Win32)
    ########################################
    - name: Build Release_x32 (Win32)
      run: msbuild vs17_dll_plugin/rtl_433.vcxproj /p:Configuration=CI_x86 /p:Platform=Win32

    - name: Upload x86 DLL
      uses: actions/upload-artifact@v4
      with:
        name: RTL_433_x86
        path: vs17_dll_plugin/CI_x86/*.dll

    ########################################
    # Build x64
    ########################################
    - name: Build Release_x64 (x64)
      run: msbuild vs17_dll_plugin/rtl_433.vcxproj /p:Configuration=CI_x64 /p:Platform=x64

    # Compute a simple version based on the commit hash
    - name: Compute VERSION
      id: compute_version
      shell: pwsh
      run: |
        # Récupère le hash court du commit HEAD
        $sha = git rev-parse --short HEAD
    
        Write-Host "Computed VERSION = $sha"
    
        # Exporte la version comme output du step
        echo "VERSION=$sha" >> $env:GITHUB_OUTPUT

    - name: Upload x64 DLL
      uses: actions/upload-artifact@v4
      with:
        name: RTL_433_x64
        path: vs17_dll_plugin\x64\CI_x64/*.dll