name: Build RTL_433 DLL

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup Visual Studio Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    ########################################
    # Build x86 (Win32)
    ########################################
    - name: Build Release_x32 (Win32)
      run: msbuild rtl_433_dll/vs17_dll_plugin/rtl_433.vcxproj /p:Configuration=Release_x32 /p:Platform=Win32

    - name: Upload x86 DLL
      uses: actions/upload-artifact@v4
      with:
        name: RTL_433_x86
        path: rtl_433_dll/vs17_dll_plugin/Release_x32/*.dll

    ########################################
    # Build x64
    ########################################
    - name: Build Release_x64 (x64)
      run: msbuild rtl_433_dll/vs17_dll_plugin/rtl_433.vcxproj /p:Configuration=Release_x64 /p:Platform=x64

    - name: Upload x64 DLL
      uses: actions/upload-artifact@v4
      with:
        name: RTL_433_x64
        path: rtl_433_dll/vs17_dll_plugin/Release_x64/*.dll
